### ISSUE TITLE
Structure lien OAuth2

### ISSUE THREAD

**Issue by les-4-noobs** [SonMaxime/Nobara.JS#1]
Bonjour, j'ai cette erreur en essayant de démarrer le bot 

internal/fs/utils.js:314
    throw err;
    ^

Error: ENOENT: no such file or directory, open './.bookman/database/main.json'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1524:35)
    at new Database (C:\Users\33752\Desktop\Nobara.JS-main\Nobara.JS-main\node_modules\bookman\dist\index.js:34:18)
    at Object.<anonymous> (C:\Users\33752\Desktop\Nobara.JS-main\Nobara.JS-main\index.js:17:13)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: './.bookman/database/main.json'

**Comment by SonMaximeIssues** [comment]
Salut ! 

Essayes de créer un dossier `/.bookman/database/` puis redémarre le bot, normalement le fichier main.json est sensé se générer tout seul. Si le fichier n'es pas généré, crée en un et ajoute les caractères {} dedans.

Bonne soirée à toi.

**Comment by les-4-noobs** [comment]
Merci beaucoup de ta réponse rapide ! 
J'ai maintenant un autre problème :


internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- C:\Users\33752\Desktop\Nobara.JS-main\Nobara.JS-main\node_modules\canvas\lib\bindings.js
- C:\Users\33752\Desktop\Nobara.JS-main\Nobara.JS-main\node_modules\canvas\lib\canvas.js
- C:\Users\33752\Desktop\Nobara.JS-main\Nobara.JS-main\node_modules\canvas\index.js
- C:\Users\33752\Desktop\Nobara.JS-main\Nobara.JS-main\events\member\guildMemberAdd.js
- C:\Users\33752\Desktop\Nobara.JS-main\Nobara.JS-main\util\loader.js
- C:\Users\33752\Desktop\Nobara.JS-main\Nobara.JS-main\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\33752\Desktop\Nobara.JS-main\Nobara.JS-main\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\33752\Desktop\Nobara.JS-main\Nobara.JS-main\node_modules\canvas\lib\canvas.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\33752\\Desktop\\Nobara.JS-main\\Nobara.JS-main\\node_modules\\canvas\\lib\\bindings.js',
    'C:\\Users\\33752\\Desktop\\Nobara.JS-main\\Nobara.JS-main\\node_modules\\canvas\\lib\\canvas.js',
    'C:\\Users\\33752\\Desktop\\Nobara.JS-main\\Nobara.JS-main\\node_modules\\canvas\\index.js',
    'C:\\Users\\33752\\Desktop\\Nobara.JS-main\\Nobara.JS-main\\events\\member\\guildMemberAdd.js',
    'C:\\Users\\33752\\Desktop\\Nobara.JS-main\\Nobara.JS-main\\util\\loader.js',
    'C:\\Users\\33752\\Desktop\\Nobara.JS-main\\Nobara.JS-main\\index.js'
  ]
}

**Comment by SonMaximeIssues** [comment]
Oula... Je crois que c'est parce que canvas n'es pas bien installé....

**Comment by les-4-noobs** [comment]
J'ai réussi Merci beaucoup (c'est vrai que le problème était évident )

**Comment by les-4-noobs** [comment]
Rebonsoir, après avoir cherché je ne trouve pas comment changer la structure du lien OAuth2 je ne trouve pas ! Si tu peux m'éclaircir  ! 

Bonne soirée

**Comment by SonMaximeIssues** [comment]
Il me semble que c'est à changer dans les paramètres de ton bot

**Comment by les-4-noobs** [comment]
Pas la structure ! 
Avant = https://discord.com/oauth2/authorize?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fcallback&scope=identify%20guilds&client_id=

maintenant = https://discord.com/api/oauth2/authorize?client_id=IDENTIFIANT&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fdashboard&response_type=code&scope=identify%20guilds

**Comment by SonMaximeIssues** [comment]
ah mais ça on ne peux pas le changer c'est un lien que seul Discord eux même peuvent modifier/simplifier (c'est pareil pour tout les bots/sites utilisant Discord)

**Comment by les-4-noobs** [comment]
Le panel ne fonctionne du coup pas ! Moi je voulais juste le changer côté bot ( mettre le nouveau )

**Comment by SonMaximeIssues** [comment]
Est-tu sur de bien avoir mis tout mis bien comme il faut du côté du fichier config et des paramètres Discord ? Tout marche bien de mon côté en local et en serveur sur ma machine de test.

**Comment by les-4-noobs** [comment]
Oui j'ai revérifié les informations et, c’est correct ! Toujours l'erreur "Invalid OAuth2 redirect uri"

**Comment by SonMaximeIssues** [comment]
Tu as changé quelque chose dans le code ?

**Comment by les-4-noobs** [comment]
non absolument rien pour l'instant

**Comment by SonMaximeIssues** [comment]
alors là pour le coup je vois vraiment pas d'où ça peut venir

**Comment by les-4-noobs** [comment]
je vais refaire le panel et je verrai forcément

**Comment by les-4-noobs** [comment]
Dans le discord developer portal il faut mettre localhost/dashboard

**Comment by les-4-noobs** [comment]
c'est good j'ai réussi !
